name: "Web export"
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: maze
  PROJECT_PATH: .

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  web-build:
    name: Web build
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Godot setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Godot web build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build/web"
  web-deploy:
    name: Web deploy
    runs-on: ubuntu-latest
    needs: web-build
    environment:
      name: GitHub Pages
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
